services:
  # El motor de base de datos
  db-postgres:
    image: postgres:15-alpine
    container_name: db-postgres
    environment:
      # Variables obligatorias de la imagen de Postgres
      DATABASE_TYPE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_NAME: go_sp_products
    ports:
      - "5435:5432"
    volumes:
      # Persistencia: para que no se borren los datos al apagar Docker
      - postgres_data:/var/lib/postgresql/data
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: 